### ISSUE TITLE
migrate this mod to "civfanatics" github org?

### ISSUE THREAD

**Issue by alexeyOnGitHub** [JLMin/ConciseUI#10]
I saw a message on Steam from the original author (? maybe the current maintainer, not the original author? either way...) where he was asking people to take over the maintenance because he no longer has the game installed, etc.
would it make sense to migrate this repo to https://github.com/civfanatics/ org to get it a new "community-owned" home?  I assume https://github.com/JLMin/ConciseUI  if the current "official" one, so we can fork this one.
we will still need to find people  to contribute to it of course, regardless of the repo location. but having it in that org may make its maintenance a bit easier.

**Comment by alexeyOnGitHub** [comment]
@JLMin hey Cat, what do you think about this?

**Comment by JLMin** [comment]
I don't like the idea that when a mod relies on too many people, it can become very difficult to maintain very soon, and we all know what CQUI has gone through.
