### ISSUE TITLE
UI Disappearing

### ISSUE THREAD

**Issue by palexdev** [JLMin/ConciseUI#14]
I don't know what's causing this but when I discover the first leader the entire UI disappears.
[Log](https://pastebin.com/64JbiRMf)
[Img1](https://imgur.com/a/baCP9PJ)
[Img2](https://imgur.com/1kWjN8Q)

Is it backwards-compatible? Because I'm playing on latest GS update 1.0.0.341

**Comment by palexdev** [comment]
Up

**Comment by Ape** [comment]
I have the same issue.

**Comment by JLMin** [comment]
new version has been rolled out, this issue should be fixed.
