### ISSUE TITLE
Incorporation of your TradeDealView into CQUI

### ISSUE THREAD

**Issue by Swarsel** [JLMin/ConciseUI#15]
Hello!

I wanted to ask if we could get your permission to add your TradeDealView into CQUI - with proper credits given, of course. Your implementation is simply the best - right now many of us are always replacing "our" version with the one that you made ^^ it would be wonderful to include it in the mod. Then we could also easier keep it up to date if updates happen.

Of course, it is totally understandable if this is not to your liking - I just figured I would ask :)

Best wishes!

**Comment by JLMin** [comment]
sure, feel free to do what ever you want.
:)
