### ISSUE TITLE
Espinoage doesn't dynamically adjust to string length causing overflow

### ISSUE THREAD

**Issue by webfischi** [JLMin/ConciseUI#7]
In the base game, the textboxes adjust dynamically to the length, in the mod they do not

![20200526025724_1](https://user-images.githubusercontent.com/22318963/82854263-379fdd80-9f08-11ea-9406-85a11bac7649.jpg)

**Comment by webfischi** [comment]
I just noticed that it should show the district name as well.
https://img.redbull.com/images/q_auto,f_auto/redbullcom/2016/10/27/1331826103504_1/auch-spione-sind-nicht-allm%C3%A4chtig.jpg

**Comment by JLMin** [comment]
district names are hidden in purpose, cause they are useless and take too much space

**Comment by webfischi** [comment]
Ok, then this was done on purpose, the top issue also shows the list this way in the popup, forgot to take a screenshot
